--- 
apiVersion: v1
kind: Service
metadata:
    name: gop-fs-service
spec:
    selector:
        app: gop-fileserver # This specification creates a new Service object named “my-service”, which targets TCP port 9376 on any Pod with the app=MyApp label.
    ports:
    - nodePort: 31200
      port: 8080
      protocol: TCP
      targetPort: 8080
    type: NodePort
---
#https://docs.openshift.com/container-platform/4.1/nodes/containers/nodes-containers-init.html
apiVersion: apps/v1
kind: Pod
#kind: Deployment
metadata:
  name: gop-fileserver
  labels:
    app: gop-fileserver
spec:
  #replicas: 1
  #selector:
  #  matchLabels:
  #    app: gop-fileserver
  template:
    metadata:
      labels:
        app: gop-fileserver
    spec:
      containers:
      - name: gop-fileserver
        image: kodekloud/fileserver                
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /web
          name: data-store
      volumes:
      - name: data-store
        persistentVolumeClaim:
          claimName: data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  storageClassName: manual
  selector:
    matchLabels:
      storage-name: data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: data-pv
 labels: 
    storage-name: data-pv
    type: local
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteMany
 capacity:
  storage: 1Gi
 hostPath:
  path: /web
