--- 
apiVersion: v1
kind: Service
metadata:
    name: gop-fs-service
spec:
    selector:
        app: gop-fileserver # This specification creates a new Service object named “my-service”, which targets TCP port 9376 on any Pod with the app=MyApp label.
    ports:
    - nodePort: 31200
      port: 8080
      protocol: TCP
      targetPort: 8080
    type: NodePort
---
apiVersion: v1
#apiVersion: apps/v1
kind: Pod
#kind: Deployment
metadata:
  name: gop-fileserver
  labels:
    app: gop-fileserver
spec:
  #replicas: 1
  #selector:
  #  matchLabels:
  #    app: gop-fileserver
  #template:
    #metadata:
    #  labels:
    #    app: gop-fileserver
    #spec:
      containers:
      - name: gop-fileserver
        image: kodekloud/fileserver                
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /web
          name: data-store
      volumes:
      - name: data-store
        persistentVolumeClaim:
          claimName: data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  storageClassName: manual
  selector:
    matchLabels:
      storage-name: data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: redis01
 labels: 
    storage-name: redis01-pv
    type: local
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 capacity:
  storage: 1Gi
 hostPath:
  path: /redis01
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: redis01
 labels: 
    storage-name: redis01-pv
    type: local
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 capacity:
  storage: 1Gi
 hostPath:
  path: /redis01
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: redis02
 labels: 
    storage-name: redis02-pv
    type: local
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 capacity:
  storage: 1Gi
 hostPath:
  path: /redis02
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: redis03
 labels: 
    storage-name: redis03-pv
    type: local
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 capacity:
  storage: 1Gi
 hostPath:
  path: /redis03
  
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: redis04
 labels: 
    storage-name: redis04-pv
    type: local
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 capacity:
  storage: 1Gi
 hostPath:
  path: /redis04
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: redis05
 labels: 
    storage-name: redis05-pv
    type: local
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 capacity:
  storage: 1Gi
 hostPath:
  path: /redis05
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: redis06
 labels: 
    storage-name: redis06-pv
    type: local
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 capacity:
  storage: 1Gi
 hostPath:
  path: /redis06
